name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up CMake
      uses: lukka/get-cmake@v3.21.2
      with:
        cmake-version: 3.21.2

    - name: Install Geode CLI
      run: |
        wget -q -O geode-cli.zip https://github.com/geode-sdk/cli/releases/v3.2.0/geode-cli-linux.zip
        unzip -q geode-cli.zip -d geode-cli
        sudo mv geode-cli/geode /usr/local/bin/
        rm -rf geode-cli geode-cli.zip

    - name: Configure CMake
      run: cmake -S . -B build

    - name: Build
      run: cmake --build build

    - name: Run tests
      run: ctest --test-dir build

    - name: Package project
      run: |
        zip -r GeodeVoiceChat.geode build/*
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: GeodeVoiceChat
        path: GeodeVoiceChat.geode
