name: CMake

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up CMake
      uses: lukka/get-cmake@v3.21.2
      with:
        cmake-version: 3.21.2

    - name: Configure CMake
      run: cmake ..

    - name: Build
      run: make

    - name: Run tests
      run: /*none*/ 
