name: CMake

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev

    - name: Set up CMake
      uses: lukka/get-cmake@v3.30.1

    - name: Configure
      run: cmake -S . -B build

    - name: Build
      run: cmake --build build
