name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up CMake
      uses: lukka/get-cmake@v3.30.1
      with:
        cmake-version: '3.26.4'  # Adjust as needed

    - name: Configure CMake
      run: cmake -S . -B build

    - name: Build
      run: cmake --build build

    - name: Package as .geode
      run: |
        mkdir -p build/releases
        # Assuming you want to package the entire project as a .geode file
        # You can adjust this command as needed
        cp -r build build/releases/GeodeVoiceChat-${{ github.sha }}.geode
        echo "PACKAGE_PATH=build/releases/GeodeVoiceChat-${{ github.sha }}.geode" >> $GITHUB_ENV

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.sha }}
        release_name: Release ${{ github.sha }}
        body: |
          Release notes for ${{ github.sha }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ env.PACKAGE_PATH }}
        asset_name: GeodeVoiceChat-${{ github.sha }}.geode
        asset_content_type: application/octet-stream
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
