name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install required packages
      run: sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev

    - name: Set up CMake
      uses: lukka/get-cmake@v3.30.1

    - name: Checkout Geode CLI repository
      run: git clone https://github.com/geode-sdk/cli.git geode-cli

    - name: Build with CMake
      run: |
        cmake -S . -B build
        cmake --build build

    - name: Verify Geode CLI installation
      run: ./geode-cli/geode --version
