name: Install Geode CLI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install-geode-cli:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake make g++ unzip

    - name: Checkout Geode CLI repository
      run: |
        git clone https://github.com/geode-sdk/cli.git geode-cli

    - name: Build Geode CLI
      run: |
        cd geode-cli
        mkdir build
        cd build
        cmake ..
        make

    - name: Verify Geode CLI installation
      run: ./geode-cli/build/geode --version
