name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Set up CMake
      uses: lukka/get-cmake@v3.30.1

    - name: Checkout Geode CLI repository
      run: git clone https://github.com/geode-sdk/cli.git geode-cli

    - name: Install Geode CLI
      run: |
        cd geode-cli
        npm install
        npm link

    - name: Configure CMake
      run: cmake -S . -B build

    - name: Build with CMake
      run: cmake --build build

    - name: Verify Geode CLI installation
      run: geode --version
