name: Create Release

on:
  push:
    branches:
      - main  # Ensure this matches your default branch

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Get the latest tag
        id: get_tag
        run: |
          git fetch --tags
          TAG=$(git tag --sort=-creatordate | head -n 1)
          echo "LATEST_TAG=$TAG" >> $GITHUB_ENV

      - name: Bump version
        id: bump_version
        run: |
          VERSION=$(echo "${LATEST_TAG#v}" | awk -F. -v OFS=. '{$NF++;print}')
          if [ -z "$VERSION" ]; then
            VERSION="1.0.0"
          fi
          echo "NEW_TAG=v$VERSION" >> $GITHUB_ENV

      - name: Create new tag
        run: |
          git tag $NEW_TAG
          git push origin $NEW_TAG

      - name: Create release
        uses: actions/create-release@v1
        with:
          tag_name: $NEW_TAG
          release_name: Release $NEW_TAG
          body: |
            Release notes for $NEW_TAG
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
