name: Create Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Fetch tags
        run: git fetch --tags

      - name: Determine the latest tag
        id: get_latest_tag
        run: |
          TAG=$(git tag --sort=-creatordate | head -n 1)
          echo "LATEST_TAG=${TAG:-v0.0.0}" >> $GITHUB_ENV

      - name: Bump version
        id: bump_version
        run: |
          VERSION=$(echo "${LATEST_TAG#v}" | awk -F. -v OFS=. '{$NF++;print}')
          if [ -z "$VERSION" ]; then
            VERSION="1.0.0"
          fi
          echo "NEW_TAG=v$VERSION" >> $GITHUB_ENV

      - name: Build GeodeVoiceChat.geode file
        run: |
          mkdir -p build
          echo "Building GeodeVoiceChat.geode file..."
          # Replace with your actual build command
          cp path/to/your/GeodeVoiceChat.geode build/GeodeVoiceChat-$NEW_TAG.geode
        env:
          NEW_TAG: ${{ env.NEW_TAG }}

      - name: Create new tag
        run: |
          git tag $NEW_TAG
          git push origin $NEW_TAG
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: $NEW_TAG
          release_name: Release $NEW_TAG
          body: |
            Release notes for $NEW_TAG
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload GeodeVoiceChat.geode file
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/GeodeVoiceChat-$NEW_TAG.geode
          asset_name: GeodeVoiceChat-$NEW_TAG.geode
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
